GNU gdb (Ubuntu 10.2-0ubuntu1~20.04~1) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(No debugging symbols found in /usr/bin/python3.8)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
(No debugging symbols found in /lib/x86_64-linux-gnu/libexpat.so.1)
(No debugging symbols found in /usr/local/lib/libz.so.1)
(No debugging symbols found in /lib/x86_64-linux-gnu/libstdc++.so.6)
(No debugging symbols found in /lib/x86_64-linux-gnu/libgcc_s.so.1)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libbz2.so.1.0)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/liblzma.so.5)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_opcode.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/../../numpy.libs/libopenblas64_p-r0-2f7c42d4.3.18.so)
(No debugging symbols found in .gnu_debugdata for /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/../../numpy.libs/libquadmath-96973f99.so.0.0.0)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/_multiarray_tests.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libffi.so.7)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/linalg/_umath_linalg.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/fft/_pocketfft_internal.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/mtrand.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/bit_generator.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_common.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_hashlib.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libcrypto.so.1.1)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_bounded_integers.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_mt19937.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_philox.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_pcg64.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_sfc64.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_generator.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/local/lib/libgmp.so.10)
(No debugging symbols found in /usr/local/lib/libfplll.so.8)
(No debugging symbols found in /lib/x86_64-linux-gnu/libqd.so.0)
(No debugging symbols found in /lib/x86_64-linux-gnu/libmpfr.so.6)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/_lib/_ccallback_c.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/_ufuncs.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/../../scipy.libs/libopenblasp-r0-085ca80a.3.9.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/../../scipy.libs/libgfortran-ed201abd.so.3.0.0)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/_ufuncs_cxx.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/specfun.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_fblas.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_flapack.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_flinalg.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_solve_toeplitz.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_decomp_update.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/cython_blas.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/cython_lapack.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/_sparsetools.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/_csparsetools.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_shortest_path.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_tools.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_traversal.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_min_spanning_tree.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_flow.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_matching.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_reordering.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/_comb.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/_ellip_harm_2.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_ssl.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libssl.so.1.1)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_queue.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_decimal.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libmpdec.so.2)
(No debugging symbols found in /usr/lib/python3/dist-packages/simplejson/_speedups.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/local/lib/python3.8/dist-packages/gmpy2/../gmpy2.libs/libmpfr-48becd64.so.6.1.0)
(No debugging symbols found in /usr/local/lib/python3.8/dist-packages/gmpy2/../gmpy2.libs/libgmp-7a47c32b.so.10.4.1)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38-x86_64-linux-gnu.so)
0x00007f266edcbc7f in __GI___wait4 (pid=76938, stat_loc=stat_loc@entry=0x0, 
    options=options@entry=0, usage=usage@entry=0x0)
    at ../sysdeps/unix/sysv/linux/wait4.c:27

Stack backtrace
---------------
    stat_loc=stat_loc@entry=0x0, options=options@entry=0, 
    usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f266edcbbfb in __GI___waitpid (pid=<optimized out>, 
    stat_loc=stat_loc@entry=0x0, options=options@entry=0) at waitpid.c:38
No locals.
#2  0x00007f266a386e74 in print_enhanced_backtrace ()
    at build/src/cysignals/implementation.c:579
        parent_pid = 31960
        pid = <optimized out>
#3  0x00007f266a386fb6 in sigdie (sig=sig@entry=6, 
    s=s@entry=0x7f266a390ab8 "Unhandled SIGABRT: An abort() occurred.")
    at build/src/cysignals/implementation.c:605
No locals.
#4  0x00007f266a389655 in sigdie_for_sig (inside=0, sig=6)
    at build/src/cysignals/implementation.c:175
No locals.
#5  cysigs_signal_handler (sig=6) at build/src/cysignals/implementation.c:278
        inside = <optimized out>
#6  <signal handler called>
No locals.
#7  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 51539607553, 140723419519856, 3, 4294967296, 
            139801185484800, 7233170478761014387, 109330211561823, 0, 0, 0, 0, 
            140723419521288, 140723419521296, 0, 140723419526600}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#8  0x00007f266ed0b859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {
            sa_handler = 0x7f266eed65c0 <_IO_2_1_stderr_>, 
            sa_sigaction = 0x7f266eed65c0 <_IO_2_1_stderr_>}, sa_mask = {
            __val = {139803046536640, 1, 139803046536771, 3432, 
              139803045108049, 14, 10, 139803046536640, 139803042641728, 
              139803033530432, 535206144, 561870554727, 139803045109395, 10, 
              139803046536640, 139803042641728}}, sa_flags = 1843356036, 
          sa_restorer = 0x7f266df0e1a2}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#9  0x00007f266dde4ee6 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#10 0x00007f266ddf6f8c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#11 0x00007f266ddf6ff7 in std::terminate() ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#12 0x00007f266ddf7258 in __cxa_throw ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#13 0x00007f266dde49ba in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#14 0x00007f266d74a40d in Siever::sample(unsigned int) ()
   from /home/cryptothesis/summer/slicer-comparison/cvp_g6k_cpu_solver/g6k/siever.cpython-38-x86_64-linux-gnu.so
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


Cython backtrace
----------------
#0  0x00007f266edcbc20 in __GI___wait4 () at /build/glibc-B3wQXB/glibc-2.31/posix/../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007f266edcbbf0 in __GI___waitpid () at /build/glibc-B3wQXB/glibc-2.31/posix/waitpid.c:38
#2  0x00007f266a386e00 in print_enhanced_backtrace () at /tmp/pip-install-ig8fe3u2/cysignals/build/src/cysignals/implementation.c:579
#3  0x00007f266a386f40 in sigdie () at /tmp/pip-install-ig8fe3u2/cysignals/build/src/cysignals/implementation.c:605
#4  0x00007f266a389442 in sigdie_for_sig () at /tmp/pip-install-ig8fe3u2/cysignals/build/src/cysignals/implementation.c:175
#5  0x00007f266a389420 in cysigs_signal_handler () at /tmp/pip-install-ig8fe3u2/cysignals/build/src/cysignals/implementation.c:278
#6  0x00007f266ef1d3e0 in __restore_rt ()
#7  0x00007f266ed2bf40 in __GI_raise () at /build/glibc-B3wQXB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:50
#8  0x00007f266ed0b72e in __GI_abort () at /build/glibc-B3wQXB/glibc-2.31/stdlib/abort.c:79
#9  0x0000000000000000 in ?? ()
#10 0x0000000000000000 in ?? ()
#11 0x0000000000000000 in std::terminate() ()
#12 0x00007f266ddf7210 in __cxa_throw ()
#13 0x0000000000000000 in ?? ()
#14 0x0000000000000000 in Siever::sample(unsigned int) ()

[Inferior 1 (process 31960) detached]
warning: .dynamic section for "/home/cryptothesis/summer/slicer-comparison/cvp_g6k_cpu_solver/g6k/siever_params.cpython-38-x86_64-linux-gnu.so" is not at the expected address (wrong library or version mismatch?)
warning: .dynamic section for "/home/cryptothesis/summer/slicer-comparison/cvp_g6k_cpu_solver/g6k/siever.cpython-38-x86_64-linux-gnu.so" is not at the expected address (wrong library or version mismatch?)
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
