GNU gdb (Ubuntu 10.2-0ubuntu1~20.04~1) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(No debugging symbols found in /usr/bin/python3.8)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
(No debugging symbols found in /lib/x86_64-linux-gnu/libexpat.so.1)
(No debugging symbols found in /usr/local/lib/libz.so.1)
(No debugging symbols found in /lib/x86_64-linux-gnu/libstdc++.so.6)
(No debugging symbols found in /lib/x86_64-linux-gnu/libgcc_s.so.1)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libbz2.so.1.0)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/liblzma.so.5)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_opcode.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/../../numpy.libs/libopenblas64_p-r0-2f7c42d4.3.18.so)
(No debugging symbols found in .gnu_debugdata for /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/../../numpy.libs/libquadmath-96973f99.so.0.0.0)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/core/_multiarray_tests.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libffi.so.7)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/linalg/_umath_linalg.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/fft/_pocketfft_internal.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/mtrand.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/bit_generator.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_common.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_hashlib.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libcrypto.so.1.1)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_bounded_integers.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_mt19937.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_philox.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_pcg64.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_sfc64.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/numpy/random/_generator.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/local/lib/libgmp.so.10)
(No debugging symbols found in /usr/local/lib/libfplll.so.8)
(No debugging symbols found in /lib/x86_64-linux-gnu/libqd.so.0)
(No debugging symbols found in /lib/x86_64-linux-gnu/libmpfr.so.6)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/_lib/_ccallback_c.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/_ufuncs.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/../../scipy.libs/libopenblasp-r0-085ca80a.3.9.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/../../scipy.libs/libgfortran-ed201abd.so.3.0.0)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/_ufuncs_cxx.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/specfun.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_fblas.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_flapack.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_flinalg.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_solve_toeplitz.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/_decomp_update.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/cython_blas.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/linalg/cython_lapack.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/_sparsetools.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/_csparsetools.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_shortest_path.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_tools.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_traversal.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_min_spanning_tree.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_flow.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_matching.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/sparse/csgraph/_reordering.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/_comb.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /home/cryptothesis/.local/lib/python3.8/site-packages/scipy/special/_ellip_harm_2.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_ssl.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libssl.so.1.1)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_queue.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_decimal.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /lib/x86_64-linux-gnu/libmpdec.so.2)
(No debugging symbols found in /usr/lib/python3/dist-packages/simplejson/_speedups.cpython-38-x86_64-linux-gnu.so)
(No debugging symbols found in /usr/local/lib/python3.8/dist-packages/gmpy2/../gmpy2.libs/libmpfr-48becd64.so.6.1.0)
(No debugging symbols found in /usr/local/lib/python3.8/dist-packages/gmpy2/../gmpy2.libs/libgmp-7a47c32b.so.10.4.1)
(No debugging symbols found in /usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38-x86_64-linux-gnu.so)
0x00007fde81c9cc7f in __GI___wait4 (pid=75249, stat_loc=stat_loc@entry=0x0, 
    options=options@entry=0, usage=usage@entry=0x0)
    at ../sysdeps/unix/sysv/linux/wait4.c:27

Stack backtrace
---------------
    stat_loc=stat_loc@entry=0x0, options=options@entry=0, 
    usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fde81c9cbfb in __GI___waitpid (pid=<optimized out>, 
    stat_loc=stat_loc@entry=0x0, options=options@entry=0) at waitpid.c:38
No locals.
#2  0x00007fde7d257e74 in print_enhanced_backtrace ()
    at build/src/cysignals/implementation.c:579
        parent_pid = 31682
        pid = <optimized out>
#3  0x00007fde7d257fb6 in sigdie (sig=sig@entry=6, 
    s=s@entry=0x7fde7d261ab8 "Unhandled SIGABRT: An abort() occurred.")
    at build/src/cysignals/implementation.c:605
No locals.
#4  0x00007fde7d25a655 in sigdie_for_sig (inside=0, sig=6)
    at build/src/cysignals/implementation.c:175
No locals.
#5  cysigs_signal_handler (sig=6) at build/src/cysignals/implementation.c:278
        inside = <optimized out>
#6  <signal handler called>
No locals.
#7  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 51539607553, 140737362512912, 3, 4294967296, 
            140591459467264, 7233170478761014387, 109330211561823, 0, 0, 0, 0, 
            140737362514344, 140737362514352, 0, 140737362519640}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#8  0x00007fde81bdc859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {
            sa_handler = 0x7fde81da75c0 <_IO_2_1_stderr_>, 
            sa_sigaction = 0x7fde81da75c0 <_IO_2_1_stderr_>}, sa_mask = {
            __val = {140593638045120, 1, 140593638045251, 3432, 
              140593636616529, 14, 10, 140593638045120, 140593634150208, 
              140593625038912, 905464992, 561870554727, 140593636617875, 10, 
              140593638045120, 140593634150208}}, sa_flags = -2134085244, 
          sa_restorer = 0x7fde80ddf1a2}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#9  0x00007fde80cb5ee6 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#10 0x00007fde80cc7f8c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#11 0x00007fde80cc7ff7 in std::terminate() ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#12 0x00007fde80cc8258 in __cxa_throw ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#13 0x00007fde80cb59ba in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#14 0x00007fde8061b40d in Siever::sample(unsigned int) ()
   from /home/cryptothesis/summer/slicer-comparison/cvp_g6k_cpu_solver/g6k/siever.cpython-38-x86_64-linux-gnu.so
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


Cython backtrace
----------------
#0  0x00007fde81c9cc20 in __GI___wait4 () at /build/glibc-B3wQXB/glibc-2.31/posix/../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007fde81c9cbf0 in __GI___waitpid () at /build/glibc-B3wQXB/glibc-2.31/posix/waitpid.c:38
#2  0x00007fde7d257e00 in print_enhanced_backtrace () at /tmp/pip-install-ig8fe3u2/cysignals/build/src/cysignals/implementation.c:579
#3  0x00007fde7d257f40 in sigdie () at /tmp/pip-install-ig8fe3u2/cysignals/build/src/cysignals/implementation.c:605
#4  0x00007fde7d25a442 in sigdie_for_sig () at /tmp/pip-install-ig8fe3u2/cysignals/build/src/cysignals/implementation.c:175
#5  0x00007fde7d25a420 in cysigs_signal_handler () at /tmp/pip-install-ig8fe3u2/cysignals/build/src/cysignals/implementation.c:278
#6  0x00007fde81dee3e0 in __restore_rt ()
#7  0x00007fde81bfcf40 in __GI_raise () at /build/glibc-B3wQXB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:50
#8  0x00007fde81bdc72e in __GI_abort () at /build/glibc-B3wQXB/glibc-2.31/stdlib/abort.c:79
#9  0x0000000000000000 in ?? ()
#10 0x0000000000000000 in ?? ()
#11 0x0000000000000000 in std::terminate() ()
#12 0x00007fde80cc8210 in __cxa_throw ()
#13 0x0000000000000000 in ?? ()
#14 0x0000000000000000 in Siever::sample(unsigned int) ()

[Inferior 1 (process 31682) detached]
warning: .dynamic section for "/home/cryptothesis/summer/slicer-comparison/cvp_g6k_cpu_solver/g6k/siever_params.cpython-38-x86_64-linux-gnu.so" is not at the expected address (wrong library or version mismatch?)
warning: .dynamic section for "/home/cryptothesis/summer/slicer-comparison/cvp_g6k_cpu_solver/g6k/siever.cpython-38-x86_64-linux-gnu.so" is not at the expected address (wrong library or version mismatch?)
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
